apiVersion: v1
kind: Service
metadata:
  name: irfantest-svc
spec:
  selector:
    app: helloirfan  
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3535
  sessionAffinity: None
  type: ClusterIP
